### ISSUE TITLE
Add configuration file

### ISSUE THREAD

**Issue by crawfordia** [nguyenmq/yt_box#11]
Initially support configuration of the following
-Socket type/address
-Video player application/arguments

**Comment by nguyenmq** [comment]
Also being able to configure a path to a file containing the cookie secret password. See the [todo here](https://github.com/nguyenmq/yt_box/blob/master/frontend/app.py#L11).

**Comment by nguyenmq** [comment]
Try this one out: https://docs.python.org/3.5/library/configparser.html

**Comment by nguyenmq** [comment]
The configuration works nicely. I made a change to it so that it reads the secret key from a separate file. This allows you to check in the configuration file without exposing the secret key to the world and the real key can be kept in a file ignored by git. Keeping the key separate also allows you to maintain tighter control over who has access to it.

I've also moved the existing cfg file to be a sample one. This way, I can keep a separate configuration that's different than the one checked into the repo.

**Comment by crawfordia** [comment]
Added configuration file in a4da196
