### ISSUE TITLE
Prevent queueing of duplicate videos

### ISSUE THREAD

**Issue by crawfordia** [nguyenmq/yt_box#7]

**Comment by nguyenmq** [comment]
The webpage now disables the submit button when a user submits a link like we talked about today. I think it should be sufficient for preventing duplicates being accidentally sent. Let me know if you figure out another way duplicates could be sent.

**Comment by nguyenmq** [comment]
I think the above solution worked well. John still managed to accidentally queue the same video a couple times, but I would blame that more on user error because he accidentally pasted the same link twice. The ability to delete your own videos from the queue should be added to help users fix accidental addds.
